[WAR Sim] Warrior Sim Initial Implementation
xiv-gear-planner/gear-planner pull request #366
Opened 2024-10-18 22:35 UTC by VioletHynes

An initial implementation of a Warrior Sim. Supports level 100.

Currently in draft while I figure out why forced crits are too high.

2024-10-19 02:17 UTC, xiashtra commented on packages/core/src/sims/sim_utils.ts
> +    if (forceDhit && forceCrit) {
I think this might cause a problem with actions that are either an autocrit or autodhit, but not both (SAM comes to mind).

2024-10-19 03:03 UTC, VioletHynes commented on packages/core/src/sims/sim_utils.ts
> +    if (forceDhit && forceCrit) {
Yeah, that's a good point -- I was mostly just doing this to test if this fixed it, but it's looking like I'll need a deeper look regardless. Thanks for pointing this out though, it's a case I'll need to look out for.

2024-10-20 23:04 UTC, VioletHynes commented on packages/xivmath/src/xivmath.ts
> +export function baseDamageFull(stats: ComputedSetStats, potency: number, attackType: AttackType = 'Unknown', autoDH: boolean = false, isDot: boolean = false): ValueWithDev {
This function was extraneously applying crit/dh for autocrits/autodhs, so it was removed from here. The multipliers are applied where they are for normal crit/dhs (`applyDhCritFull`).

2024-10-20 23:28 UTC, VioletHynes commented on packages/xivmath/src/xivmath.ts
> +        forcedCrit ? chanceMultiplierStdDev(1, stats.critMulti) : chanceMultiplierStdDev(stats.critChance, stats.critMulti),
This could be expressed as e.g. `chanceMultiplierStdDev(forcedCrit ? 1 : stats.critChance, stats.critMulti)`, but I think it reads more immediately obviously this way.

2024-10-21 14:27 UTC, xpdota commented
Looks good. Would you mind adding some tests for auto-dh to validate against known results?

2024-10-21 16:43 UTC, amakiirs reviewed
I don't have any major complaints, and nor did I see any particular issues rotationally, but I don't want to approve immediately due to my lack of detailed WAR knowledge. If no one with more experience looks at it, I can give another pass and read up more.

2024-10-21 21:19 UTC, amakiirs requested changes
Correct me if I'm wrong, but I *think* the inBurst check isn't quite right.

This might (in principle anyway) be another thing to pull out into a separate function, but I'm not quite sure what that would look like. Something of the form `inTimeRangeMod(start, end, mod)`, maybe, but that's a bit awkward to understand the meaning of from the name, especially with three parameters.

2024-10-21 21:19 UTC, amakiirs commented on packages/core/src/sims/tank/war/war_sheet_sim.ts
>          return this.currentTime % 126 < 20
With this explanation, I think it should instead be something closer to:
```typescript
const timeIntoTwoMinutes = this.currentTime % 120 // This isn't a great name but I don't have a better one offhand
return 6 <= timeIntoTwoMinutes && timeIntoTwoMinutes < 26
```
A code-cleaner but harder to understand version:
```typescript
// + 114 and -6 are equivalent mod 120, but because mod with a negative number yields a negative result,
// + 114 avoids awkwardness at low times that results from -6
return ((this.currentTime + 114) % 120) < 20
```

2024-10-21 21:36 UTC, VioletHynes commented on packages/core/src/sims/tank/war/war_sheet_sim.ts
>          return this.currentTime % 126 < 20
Good catch -- fixed

2024-10-21 21:42 UTC, amakiirs approved these changes
Looks fine to me at this point, and I again don't see any obvious problems in the rotation generation.

2024-10-22 01:53 UTC, VioletHynes commented on packages/core/src/test/datamanager_tests.ts
> -describe('Old Datamanager', () => {
I deleted these, as they weren't running until this PR, were failing, and this seems unused

2024-10-22 02:00 UTC, merged