Buff dot improvements 2
xiv-gear-planner/gear-planner pull request #90
Opened 2024-04-28 15:09 UTC by xpdota

2024-05-01 23:01 UTC, xiashtra requested changes
Attempting to have a gcd action that applies an indefinite duration buff causes the buff to not be applied at all.

2024-05-02 00:23 UTC, xiashtra commented
Infinite duration buffs do not work at all with this PR.

2024-05-02 00:40 UTC, xpdota commented on packages/frontend/src/scripts/sims/blu/blu_common.ts
> +} as const satisfies Buff; // This allows the 'indefinite' check to be skipped
Hmm, I think these end up not being needed. I needed them at one point to make it compile without having additional checks within the BLU-specific sim code.

2024-05-02 12:44 UTC, xiashtra commented
> Should all be addressed now

Working as expected now.

2024-05-02 13:19 UTC, merged